fix(spring_test): 디버깅

diff --git a/.github/workflows/spring_test.yml b/.github/workflows/spring_test.yml
--- a/.github/workflows/spring_test.yml
+++ b/.github/workflows/spring_test.yml
@@ -35,17 +35,18 @@ jobs:
       #       ${{ runner.os }}-gradle-
 
       - name: Start Docker Compose and wait for database
+        env:
+          DB_USERNAME: ${{ secrets.DB_USERNAME }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
+          DB_HOST_PORT: ${{ secrets.DB_HOST_PORT }}
+          DB_CONTAINER_PORT: ${{ secrets.DB_CONTAINER_PORT }}
+          DB_NAME: ${{ secrets.DB_NAME }}
+          DB_CONTAINER_NAME: ${{ secrets.DB_CONTAINER_NAME }}
         run: |
           chmod +x ./gradlew
           cd ./docker
-          docker compose up -d \
-            -e DB_USERNAME="${{secrets.DB_USERNAME}}" \
-            -e DB_PASSWORD="${{secrets.DB_PASSWORD}}" \
-            -e DB_ROOT_PASSWORD="${{secrets.DB_ROOT_PASSWORD}}" \
-            -e DB_HOST_PORT="${{secrets.DB_HOST_PORT}}" \
-            -e DB_CONTAINER_PORT="${{secrets.DB_CONTAINER_PORT}}" \
-            -e DB_NAME="${{secrets.DB_NAME}}" \
-            -e DB_CONTAINER_NAME="${{secrets.DB_CONTAINER_NAME}}"
+          docker compose run -d
           # Wait for database to be ready
           echo "Waiting for database to be ready..."
           timeout 60s bash -c 'until docker exec -i $(docker ps -q --filter "name=db") mysqladmin ping -h "127.0.0.1" --silent; do sleep 1; done'
@@ -54,7 +55,19 @@ jobs:
         run: ./gradlew build -x test
 
       - name: Run Tests
-        run: ./gradlew test
+        run: ./gradlew --info test
+
+      - name: Publish Unit Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v1
+        if: ${{ always() }}
+        with:
+          files: build/test-results/**/*.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
 
       - name: Package the application
         run: ./gradlew assemble
